### ISSUE TITLE
TypeError (prob because development is still active)

### ISSUE THREAD

**Issue by filippo-fonseca** [alii/discord-landing-page#1]
This might be because it's still in development, but I thought I'd let you know just in case. :)

<img width="1027" alt="Screen Shot 2021-01-02 at 11 22 21" src="https://user-images.githubusercontent.com/48065878/103462731-f026ce80-4cec-11eb-8554-06e49106c489.png">

**Comment by alii** [comment]
This is an issue with your environment variables. Ensure that you have configured them properly and it will work 👍🏻
